@startuml
hide methods
hide circle

class Administrator{
}

class Employee{
}

class Coordinator{
}

class Receptionist{
}

class Nurse{
}

class Company{
}

Nurse"1..*" -up- "1"Employee : > play as
Receptionist"1..*" -up- "1"Employee : > play as
Coordinator"1..*" -up- "1"Employee : > play as
Company"1" -left- "1..*"Administrator : > has
Administrator"1" -left-"1..*"Employee : > creates



@enduml