@startuml
'https://plantuml.com/class-diagram

class User{
+ getVaccineAdministrationStore();
}

class Company{
+ getUserStore();
+ getAuthFacade();
}

class UserStore{
+ findUserFullyVaccinatedOnIntervalAndCenter(start,end,actorCenter);
}

class VaccineAdministrationStore{
+verifyIfIsFullyVaccinatedOnInterval(Date start, Date end, VaccinationCenter center);
}

class ExportVaccinationStatisticsController{
+ ExportVaccinationStatisticsController();
+ getUsersFullyVaccinatedOnIntervalAndCenter(Date start, Date end)
}

class ExportVaccinationStatisticsGUI{
+ start(Stage stage);
}

class ExportVaccinationStatisticsUI{
+ submitBtnClick(ActionEvent event);
}

Company .right.> UserStore : knows
ExportVaccinationStatisticsUI .> ExportVaccinationStatisticsController
ExportVaccinationStatisticsController ..> Company
ExportVaccinationStatisticsController ..> UserStore : uses
ExportVaccinationStatisticsGUI ..> ExportVaccinationStatisticsUI : uses
UserStore"1" --> "*"User : has
User"1" --> "1"VaccineAdministrationStore : has



@enduml